project:
  type: website
  output-dir: docs
website:
  title: "My Blog"
  site-url: https://www.niharikabalachandra.com
  description: "Niharika's blog where data points weave stories, and algorithmic solutions propel us toward a clearer, more informed future. "
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/niharikabalachandra
      - icon: linkedin
        href: https://www.linkedin.com/in/niharikabalachandra/
      - icon: rss
        href: index.xml 
format:
  html:
    theme: cosmo
    css: styles.css

