project:
  type: website
  output-dir: docs
website:
  title: "Niharika's blog"
  site-url: https://www.niharikabalachandra.com
  description: "Niharika's blog where data points weave stories, and algorithmic solutions propel us toward a clearer, more informed future. "
  cookie-consent: true
  google-analytics: "G-HW7V68ZHXG"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/niharikabalachandra
      - icon: linkedin
        href: https://www.linkedin.com/in/niharikabalachandra/
      - icon: medium
        href: https://medium.com/@niharikabalachandra
      - icon: bi bi-gift
        href: https://www.buymeacoffee.com/niharikaba1
      - icon: rss
        href: index.xml 
  page-footer: 
    left: "Copyright 2024, Niharika Balachandra" 
format:
  html:
    theme: cosmo
    css: styles.css

